# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
aliases:
  - &environment
      resource_class: xlarge
      working_directory: ~/prebid-universal-creative

jobs:
  unit-tests:
    <<: *environment
    docker:
      - image: cimg/node:20.14.0-browsers

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-unit-{{ checksum "package.json" }}
            - v1-dependencies-unit
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-unit-{{ checksum "package.json" }}
      - run:
          name: Install gulp cli
          command: sudo npm install -g gulp-cli
      - run:
          name: BrowserStack testing
          command: gulp test --browserstack

  integ-tests:
    <<: *environment
    docker:
      - image: mcr.microsoft.com/playwright:v1.26.0-focal
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-integ-{{ checksum "package.json" }}
            - v1-dependencies-iteg
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-integ-{{ checksum "package.json" }}
      - run:
          name: Build
          command: npx gulp build
      - run:
          name: Install playwright browsers
          command: npx playwright install --with-deps
      - run:
          name: Integ tests
          command: npx playwright test
workflows:
  version: 2
  commit:
    jobs:
      - unit-tests
      - integ-tests
